### ISSUE TITLE
asignment 8 how do i take alphabets

### ISSUE THREAD

**Issue by 32bit23** [vtcbca/basic-programming-32bit23#2]
how do i take aphabets

**Comment by 32bit23** [comment]
you frist you declare variables

**Comment by 82bit23** [comment]
my variables are declared int and char

**Comment by 32bit23** [comment]
ok and secend take for loop statments

**Comment by 82bit23** [comment]
ok

**Comment by 32bit23** [comment]
and another for loop statment add

**Comment by 32bit23** [comment]
but you craete error

**Comment by 82bit23** [comment]
Bhai alphabet repert your letters
